// This file is part of Substrate.

// Copyright (C) 2022 Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for pallet_protos
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-10-13, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! HOSTNAME: `alepc`, CPU: `11th Gen Intel(R) Core(TM) i7-1195G7 @ 2.90GHz`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/production/clamor
// benchmark
// pallet
// --chain=dev
// --steps=50
// --repeat=20
// --pallet=pallet_protos
// --extrinsic=*
// --execution=wasm
// --wasm-execution=compiled
// --heap-pages=4096
// --output=./pallets/protos/src/weights.rs
// --template=./.maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_protos.
pub trait WeightInfo {
	fn upload(r: u32, t: u32, d: u32, ) -> Weight;
	fn patch(r: u32, t: u32, d: u32, ) -> Weight;
	fn detach() -> Weight;
	fn transfer() -> Weight;
	fn set_metadata(m: u32, d: u32, ) -> Weight;
}

/// Weights for pallet_protos using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	// Storage: Protos Protos (r:2 w:1)
	// Storage: unknown [0x3a65787472696e7369635f696e646578] (r:1 w:0)
	// Storage: Protos Tags (r:100 w:100)
	// Storage: Protos TagsIndex (r:1 w:1)
	// Storage: Protos ProtosByCategory (r:1 w:1)
	// Storage: Protos ProtosByOwner (r:1 w:1)
	/// The range of component `r` is `[1, 100]`.
	/// The range of component `t` is `[1, 100]`.
	/// The range of component `d` is `[1, 1000000]`.
	fn upload(r: u32, t: u32, d: u32, ) -> Weight {
		Weight::from_ref_time(95_041_000 as u64)
			// Standard Error: 65_000
			.saturating_add(Weight::from_ref_time(2_092_000 as u64).saturating_mul(r as u64))
			// Standard Error: 65_000
			.saturating_add(Weight::from_ref_time(2_860_000 as u64).saturating_mul(t as u64))
			// Standard Error: 0
			.saturating_add(Weight::from_ref_time(2_000 as u64).saturating_mul(d as u64))
			.saturating_add(T::DbWeight::get().reads(5 as u64))
			.saturating_add(T::DbWeight::get().reads((1 as u64).saturating_mul(r as u64)))
			.saturating_add(T::DbWeight::get().reads((1 as u64).saturating_mul(t as u64)))
			.saturating_add(T::DbWeight::get().writes(4 as u64))
			.saturating_add(T::DbWeight::get().writes((1 as u64).saturating_mul(t as u64)))
	}
	// Storage: Protos Protos (r:2 w:1)
	// Storage: Detach DetachedHashes (r:1 w:0)
	// Storage: unknown [0x3a65787472696e7369635f696e646578] (r:1 w:0)
	// Storage: Protos Tags (r:100 w:100)
	// Storage: Protos TagsIndex (r:1 w:1)
	/// The range of component `r` is `[1, 100]`.
	/// The range of component `t` is `[1, 100]`.
	/// The range of component `d` is `[1, 1000000]`.
	fn patch(r: u32, t: u32, d: u32, ) -> Weight {
		Weight::from_ref_time(0 as u64)
			// Standard Error: 198_000
			.saturating_add(Weight::from_ref_time(2_254_000 as u64).saturating_mul(r as u64))
			// Standard Error: 198_000
			.saturating_add(Weight::from_ref_time(3_096_000 as u64).saturating_mul(t as u64))
			// Standard Error: 0
			.saturating_add(Weight::from_ref_time(2_000 as u64).saturating_mul(d as u64))
			.saturating_add(T::DbWeight::get().reads(4 as u64))
			.saturating_add(T::DbWeight::get().reads((1 as u64).saturating_mul(r as u64)))
			.saturating_add(T::DbWeight::get().reads((1 as u64).saturating_mul(t as u64)))
			.saturating_add(T::DbWeight::get().writes(2 as u64))
			.saturating_add(T::DbWeight::get().writes((1 as u64).saturating_mul(t as u64)))
	}
	// Storage: Protos Protos (r:1 w:0)
	// Storage: Detach DetachedHashes (r:1 w:0)
	// Storage: Detach DetachRequests (r:1 w:1)
	fn detach() -> Weight {
		Weight::from_ref_time(13_387_000 as u64)
			.saturating_add(T::DbWeight::get().reads(3 as u64))
			.saturating_add(T::DbWeight::get().writes(1 as u64))
	}
	// Storage: Protos Protos (r:1 w:1)
	// Storage: Detach DetachedHashes (r:1 w:0)
	// Storage: Protos ProtosByOwner (r:2 w:2)
	fn transfer() -> Weight {
		Weight::from_ref_time(24_381_000 as u64)
			.saturating_add(T::DbWeight::get().reads(4 as u64))
			.saturating_add(T::DbWeight::get().writes(3 as u64))
	}
	// Storage: Protos Protos (r:1 w:1)
	// Storage: Detach DetachedHashes (r:1 w:0)
	// Storage: unknown [0x3a65787472696e7369635f696e646578] (r:1 w:0)
	// Storage: Protos MetaKeys (r:1 w:1)
	// Storage: Protos MetaKeysIndex (r:1 w:1)
	/// The range of component `m` is `[1, 100]`.
	/// The range of component `d` is `[1, 1000000]`.
	fn set_metadata(m: u32, d: u32, ) -> Weight {
		Weight::from_ref_time(0 as u64)
			// Standard Error: 90_000
			.saturating_add(Weight::from_ref_time(122_000 as u64).saturating_mul(m as u64))
			// Standard Error: 0
			.saturating_add(Weight::from_ref_time(2_000 as u64).saturating_mul(d as u64))
			.saturating_add(T::DbWeight::get().reads(5 as u64))
			.saturating_add(T::DbWeight::get().writes(3 as u64))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	// Storage: Protos Protos (r:2 w:1)
	// Storage: unknown [0x3a65787472696e7369635f696e646578] (r:1 w:0)
	// Storage: Protos Tags (r:100 w:100)
	// Storage: Protos TagsIndex (r:1 w:1)
	// Storage: Protos ProtosByCategory (r:1 w:1)
	// Storage: Protos ProtosByOwner (r:1 w:1)
	/// The range of component `r` is `[1, 100]`.
	/// The range of component `t` is `[1, 100]`.
	/// The range of component `d` is `[1, 1000000]`.
	fn upload(r: u32, t: u32, d: u32, ) -> Weight {
		Weight::from_ref_time(95_041_000 as u64)
			// Standard Error: 65_000
			.saturating_add(Weight::from_ref_time(2_092_000 as u64).saturating_mul(r as u64))
			// Standard Error: 65_000
			.saturating_add(Weight::from_ref_time(2_860_000 as u64).saturating_mul(t as u64))
			// Standard Error: 0
			.saturating_add(Weight::from_ref_time(2_000 as u64).saturating_mul(d as u64))
			.saturating_add(RocksDbWeight::get().reads(5 as u64))
			.saturating_add(RocksDbWeight::get().reads((1 as u64).saturating_mul(r as u64)))
			.saturating_add(RocksDbWeight::get().reads((1 as u64).saturating_mul(t as u64)))
			.saturating_add(RocksDbWeight::get().writes(4 as u64))
			.saturating_add(RocksDbWeight::get().writes((1 as u64).saturating_mul(t as u64)))
	}
	// Storage: Protos Protos (r:2 w:1)
	// Storage: Detach DetachedHashes (r:1 w:0)
	// Storage: unknown [0x3a65787472696e7369635f696e646578] (r:1 w:0)
	// Storage: Protos Tags (r:100 w:100)
	// Storage: Protos TagsIndex (r:1 w:1)
	/// The range of component `r` is `[1, 100]`.
	/// The range of component `t` is `[1, 100]`.
	/// The range of component `d` is `[1, 1000000]`.
	fn patch(r: u32, t: u32, d: u32, ) -> Weight {
		Weight::from_ref_time(0 as u64)
			// Standard Error: 198_000
			.saturating_add(Weight::from_ref_time(2_254_000 as u64).saturating_mul(r as u64))
			// Standard Error: 198_000
			.saturating_add(Weight::from_ref_time(3_096_000 as u64).saturating_mul(t as u64))
			// Standard Error: 0
			.saturating_add(Weight::from_ref_time(2_000 as u64).saturating_mul(d as u64))
			.saturating_add(RocksDbWeight::get().reads(4 as u64))
			.saturating_add(RocksDbWeight::get().reads((1 as u64).saturating_mul(r as u64)))
			.saturating_add(RocksDbWeight::get().reads((1 as u64).saturating_mul(t as u64)))
			.saturating_add(RocksDbWeight::get().writes(2 as u64))
			.saturating_add(RocksDbWeight::get().writes((1 as u64).saturating_mul(t as u64)))
	}
	// Storage: Protos Protos (r:1 w:0)
	// Storage: Detach DetachedHashes (r:1 w:0)
	// Storage: Detach DetachRequests (r:1 w:1)
	fn detach() -> Weight {
		Weight::from_ref_time(13_387_000 as u64)
			.saturating_add(RocksDbWeight::get().reads(3 as u64))
			.saturating_add(RocksDbWeight::get().writes(1 as u64))
	}
	// Storage: Protos Protos (r:1 w:1)
	// Storage: Detach DetachedHashes (r:1 w:0)
	// Storage: Protos ProtosByOwner (r:2 w:2)
	fn transfer() -> Weight {
		Weight::from_ref_time(24_381_000 as u64)
			.saturating_add(RocksDbWeight::get().reads(4 as u64))
			.saturating_add(RocksDbWeight::get().writes(3 as u64))
	}
	// Storage: Protos Protos (r:1 w:1)
	// Storage: Detach DetachedHashes (r:1 w:0)
	// Storage: unknown [0x3a65787472696e7369635f696e646578] (r:1 w:0)
	// Storage: Protos MetaKeys (r:1 w:1)
	// Storage: Protos MetaKeysIndex (r:1 w:1)
	/// The range of component `m` is `[1, 100]`.
	/// The range of component `d` is `[1, 1000000]`.
	fn set_metadata(m: u32, d: u32, ) -> Weight {
		Weight::from_ref_time(0 as u64)
			// Standard Error: 90_000
			.saturating_add(Weight::from_ref_time(122_000 as u64).saturating_mul(m as u64))
			// Standard Error: 0
			.saturating_add(Weight::from_ref_time(2_000 as u64).saturating_mul(d as u64))
			.saturating_add(RocksDbWeight::get().reads(5 as u64))
			.saturating_add(RocksDbWeight::get().writes(3 as u64))
	}
}
